author = "HungTran"
description = "Hung Tran Duy's resume"

primaryColor = "#8fbcbb"
textPrimaryColor = "#292929"

[floatingbutton]
    enable = true
    downloadButton = true

[profile]
    enable = true
    name = "Trần Duy Hưng"
    tagline = "Backend Software Engineer"
    avatar = "avatar1.jpeg"

[contact]
    enable = true

    [[contact.list]]
    icon = "fas fa-phone-square"
    url = "tel:#"
    text = "0985 119 197"
    [[contact.list]]
    icon = "fas fa-envelope-square"
    url = "mailto:#"
    text = "hungtrd.dev@gmail.com"
    [[contact.list]]
    icon = "fas fa-globe"
    url = "https://hung.cafe"
    text = "hung.cafe"
    [[contact.list]]
    icon = "fas fa-map-marker-alt"
    url = "https://maps.app.goo.gl/r7uk47Hzc8Fojytj6"
    text = "Hà Nội, Việt Nam"

[skills]
    enable = true

    [[skills.list]]
    title = "Technical"
    [[skills.list.items]]
    details = "JavaScript/Angular/React/Vue"
    [[skills.list.items]]
    details = "Python/Ruby/PHP"
    [[skills.list.items]]
    details = "Node.js/ASP.NET"
    [[skills.list.items]]
    details = "PostgreSQL/MySQL"
    [[skills.list.items]]
    details = "Object-oriented design"
    [[skills.list.items]]
    details = "Design and implement database structures"
    [[skills.list.items]]
    details = "Lead and deliver complex software systems"

    [[skills.list]]
    title = "Professional"
    [[skills.list.items]]
    details = "Effective communication"
    [[skills.list.items]]
    details = "Team player"
    [[skills.list.items]]
    details = "Strong problem solver"
    [[skills.list.items]]
    details = "Good time management"

[education]
    enable = true

    [[education.list]]
    degree = "Công nghệ phần mềm"
    university = "Học viện Công nghệ Bưu chính Viễn thông Hà Nội - PTIT"
    dates = ""
    [[education.list]]
    degree = "Chuyên Tin"
    university = "Trường Trung học phổ thông chuyên Thái Bình"
    dates = ""

[awards]
    enable = true

    [[awards.list]]
    name = "Award Lorem Ipsum"
    body = "Microsoft lorem ipsum"
    date = "2019"
    [[awards.list]]
    name = "Award Donec Sodales"
    body = "Oracle Aenean"
    date = "2017"

[languages]
    enable = true

    [[languages.list]]
    name = "Tiếng Việt"
    level = "Tiếng bản xứ"
    [[languages.list]]
    name = "Tiếng Anh"
    level = "TOEIC 600+"

[interests]
    enable = true

    [[interests.list]]
    name = "Climbing"
    [[interests.list]]
    name = "Snowboarding"
    [[interests.list]]
    name = "Photography"
    [[interests.list]]
    name = "Travelling"

[summary]
    enable = true
    text = "Là người có niềm yêu thích với công nghệ, mong muốn trải nghiệm những sản phẩm công nghệ mới. Từ đó tôi luôn mong muốn tạo ra những sản phẩm tốt cho người dùng. Với khả năng học tập nhanh và tư duy tốt, tôi muốn được học hỏi thêm từ những người đi trước giàu kinh nghiệm, giúp cải thiện bản thân từ đó nâng cao kỹ năng chuyên môn back-end và đóng góp giúp công ty phát triển hơn."

[experience]
    enable = true

    [[experience.list]]
    title = "Senior Software Engineer"
    dates = "2019 - Present"
    company = "Google"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
    [[experience.list.items]]
    details = "Lorem ipsum dolor sit amet, consectetuer."
    [[experience.list.items]]
    details = "Aenean commodo ligula eget dolor."
    [[experience.list.items]]
    details = "Etiam ultricies nisi vel augue."

    [[experience.list]]
    title = "Lead Software Developer"
    dates = "2016 - 2019"
    company = "Apple"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
    [[experience.list.items]]
    details = "Lorem ipsum dolor sit amet, consectetuer."
    [[experience.list.items]]
    details = "Aenean commodo ligula eget dolor."

    [[experience.list]]
    title = "Senior Software Developer"
    dates = "2014 - 2016"
    company = "Dropbox"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[experience.list]]
    title = "Senior Developer"
    dates = "2013 - 2014"
    company = "Uber"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [[experience.list]]
    title = "Backend Developer"
    dates = "2014 - 2016"
    company = "Amazon"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[experience.list]]
    title = "Frontend Developer"
    dates = "2013 - 2014"
    company = "Startup"
    details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

[projects]
    enable = true

    [[projects.list]]
    title = "Project Lorem Ipsum"
    meta = "Open Source"
    tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

    [[projects.list]]
    title = "Project Sed Fringilla"
    meta = "Open Source"
    tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [[projects.list]]
    title = "Project Praesent"
    meta = "Open Source"
    tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

[information]
    enable = true

    [[information.list]]
    title = "Papers"
    [[information.list.items]]
    details = "2018 · Lorem Ipsum"
    [[information.list.items]]
    details = "2016 · Sed Fringilla"

    [[information.list]]
    title = "Interests"
    details = "Climbing, Snowboarding, Photography, Travelling"

[social]
    enable = true

    [[social.list]]
    icon = "fab fa-github-square"
    url = "https://github.com/hungtrd"
    title = "hungtrd"
    [[social.list]]
    icon = "fab fa-linkedin"
    url = "//linkedin.com/in/username"
    title = "username"
    [[social.list]]
    icon = "fab fa-facebook-square"
    url = "https://www.facebook.com/hungtrd/"
    title = "hungtrd"
    # [[social.list]]
    # icon = "fab fa-twitter-square"
    # url = "https//twitter.com/username"
    # title = "@username"

