# Page settings

baseURL = "https://huzg.me/"
languageCode = "en-us"
title = "Hung Tran Duy 's resume"
theme = "devresume"
googleAnalytics = "UA-XXXXXXX-Y"

# disableLanguages = ['vi', 'fr']

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
