# Page settings

baseURL = "https://huzg.me/"
languageCode = "en-us"
title = "Hung Tran Duy 's resume"
theme = "devresume"
googleAnalytics = "UA-XXXXXXX-Y"

# disableLanguages = ['vi', 'fr']
[languages.vi]
contentDir = 'content/vi'
languageCode = 'vi-VN'
languageName = 'Vietnamese'
weight = 1

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 2

[caches]
  [caches.assets]
    dir = ':resourceDir/_gen'
    maxAge = -1
